Adding cloud run job to initialize the database

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -120,6 +120,30 @@ jobs:
           docker build --target ${{ env.ENVIRONMENT }} -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest" ./backend
           docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest"
 
+      - name: Initialize Database
+        run: |-
+          JOB_NAME="db-init-${{ github.run_number }}"
+
+          gcloud run jobs create ${JOB_NAME} \
+            --image "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest" \
+            --region ${{ env.REGION }} \
+            --tasks 1 \
+            --service-account=${{ vars.WIF_SERVICE_ACCOUNT }} \
+            --add-cloudsql-instances=${{ env.PROJECT_ID }}:us-east1:devil-fruit-database-psql-id \
+            --set-env-vars="PYTHONPATH=../,ENVIRONMENT=${{ env.ENVIRONMENT }},GCP_SQL_INSTANCE_CONNECTION_NAME=${{ env.PROJECT_ID }}:us-east1:devil-fruit-database-psql-id,POSTGRES_DB=${{ env.POSTGRES_DB }},POSTGRES_USER=${{ secrets.POSTGRES_USER }},POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" \
+            --command "python" \
+            --args "-m,app.core.db_management,force-reset,--env,${{ env.ENVIRONMENT }}"
+
+          gcloud run jobs execute ${JOB_NAME} --region ${{ env.REGION }} --wait
+
+          # Check job status
+          STATUS=$(gcloud run jobs executions list --job ${JOB_NAME} --region ${{ env.REGION }} --format='get(status.conditions[0].type)')
+
+          if [ "$STATUS" != "Succeeded" ]; then
+            echo "Job failed with status: $STATUS"
+            exit 1
+          fi
+
       - name: Deploy to Cloud Run
         id: deploy
         uses: google-github-actions/deploy-cloudrun@v2.7.0
